CREATE DATABASE IF NOT EXISTS alx_book_store;
USE alx_book_store;

CREATE TABLE IF NOT EXISTS Authors (...);
CREATE TABLE IF NOT EXISTS Books (...);
CREATE TABLE IF NOT EXISTS Customers (...);
CREATE TABLE IF NOT EXISTS Orders (...);
CREATE TABLE IF NOT EXISTS Order_Details (...);
